name: Deploy React Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Change this if you use a different branch for deployment

permissions:
  contents: write # Grant write permissions to contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: |
          echo "NODE_ENV=${NODE_ENV}" >> $GITHUB_ENV
          echo "VITE_APP_BASE_URL=${VITE_APP_BASE_URL}" >> $GITHUB_ENV
          echo "VITE_ENABLE_MSW=${VITE_ENABLE_MSW}" >> $GITHUB_ENV
          bun run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          VITE_APP_BASE_URL: ${{ env.VITE_APP_BASE_URL }}
          VITE_ENABLE_MSW: ${{ env.VITE_ENABLE_MSW }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Provided automatically by GitHub Actions
          publish_dir: ./dist # The directory where your built files are located
          publish_branch: gh-pages # Branch where the built files will be pushed
