name: Deploy React Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Change this if you use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build
        env: 
          NODE_ENV: ${{ env.NODE_ENV }}
          VITE_APP_BASE_URL: ${{ env.VITE_APP_BASE_URL }}
          VITE_ENABLE_MSW: ${{ env.VITE_ENABLE_MSW }}
          

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Provided automatically by GitHub Actions
          publish_dir: ./dist # The directory where your built files are located
          publish_branch: gh-pages # Branch where the built files will be pushed

